### ISSUE TITLE
Missing icon classes for buttons

### ISSUE THREAD

**Issue by sebolio** [loadingio/ldbutton#1]
I followed the instructions on buttons page and downloaded the zipped CSS file, however it doesn't contain the animation classes like ld-ring or ld-spin, which appear to be on the styl files but not on the distributed CSS.

Also worth noting that stylus files located in src folder are not compatible with any official compiler, and aren't compatible with VueJS CLI.

CSS used: https://github.com/loadingio/ldbutton/releases/latest/download/ldbtn.min.css

**Comment by michaelthedev** [comment]
Hi @sebolio 
Did you include the regular loading.css?
https://cdn.jsdelivr.net/gh/loadingio/loading.css@v2.0.0/dist/loading.css

You need the loading.css cause it contains the loading icons
Source: https://loading.io/animation/

**Comment by zbryikt** [comment]
yes and sorry for this confusion; I think additional information should be added in the sample code section inside README about loading.css to make it more clear for users; will keep this issue opened until we update the doc. :)

**Comment by sebolio** [comment]
it's been 3 years

**Comment by zbryikt** [comment]
We have made sure that both README and https://loading.io/button/ and confirmed that there are information about loading.css; additionally a note is added in the usage section of the online document. 

To minimize confusion, I think it may be good to add a minimal set of loader directly in ldbutton, however I think we can open another issue to discuss this if needed, so I'll close this issue for now.
