### ISSUE TITLE
Loading Buttons Download link broken

### ISSUE THREAD

**Issue by a-ryang** [loadingio/ldbutton#6]
https://loading.io/button/

I found `Download Now` button link is broken.
I suggest change to https://github.com/loadingio/ldbutton/releases/download/v2.0.1/index.min.css
from https://github.com/loadingio/ldbutton/releases/download/v2.0.1/ldbtn.min.css

**Comment by zbryikt** [comment]
thanks! will fix this in the following release

**Comment by zbryikt** [comment]
have it patched and made sure all other links to the css file correctly.
